import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/components/Provider'
import Navbar from '@/components/Navbar'
import { getSession } from '@/actions/getCurrentUser'
import Login from '@/components/login/login'
import createUser from '@/actions/createUser'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getSession()



  return (
    <html lang="en">
      <body className={inter.className}>
        {
          !session ? <Login /> : (
            <Provider>
              <div className="bg-blue-900 min-h-screen flex">
                <Navbar />
                <div className="bg-white flex-grow mt-1 mr-1 mb-2 rounded-lg p-4">
                  {children}
                </div>
              </div>
            </Provider>
          )
        }
      </body>
    </html>
  )
}
